apply plugin: 'com.android.application'

android {
    namespace 'com.fuelregister.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.fuelregister.app"
        minSdk 24
        targetSdk 34
        versionCode 17
        versionName "1.3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
